// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvVOdXRB9kZOswY1r3HG0cKIj99SQER78',
    appId: '1:333792263271:android:49293963d264092a6d68c2',
    messagingSenderId: '333792263271',
    projectId: 'cse4186-ff4e8',
    databaseURL: 'https://cse4186-ff4e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cse4186-ff4e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhAceAGNtXdt5MoMb59YEInbR62XriAeE',
    appId: '1:333792263271:ios:6f0994dcc487122a6d68c2',
    messagingSenderId: '333792263271',
    projectId: 'cse4186-ff4e8',
    databaseURL: 'https://cse4186-ff4e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cse4186-ff4e8.appspot.com',
    iosClientId: '333792263271-jbhiimt5fcks437bcf9fujv9acj2nqpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
